config/routes.rb
Rails.application.routes.draw do
  resources :books
  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # before_action specifies something we want to do before any of the following actions/mothods are used / initiated
  before_action :find_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.all.order("created_at DESC")
  end

  def new
    @book ||= Book.new
  end

  def show
  end

  def edit
  end

  def destroy
    @book.destroy
    redirect_to root_path
  end

  # create / update wont have their own views; just redirect statements
  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to root_path
    else
      # when you 'render', you're rendering another action within the controller-- not necessarily a view per se,
      # but specifically the action and its methods prior to its associated view
      new
    end
  end

  def update
    # if book is updated successfully, display edit view with form to edit what's already available
    # book_params is going to be changed
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  private
    def book_params
      params.require(:book).permit(:title, :description, :author)
    end

    def find_book
      @book = Book.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
  <%= f.input :title, label: "Book Title", wrapper_html: { class: 'm6 s12' } %>
  <%= f.input :description, wrapper_html: { class: 'm6 s12' } %>
  <%= f.input :author, wrapper_html: { class: 'm6 s12' } %>
  <%= f.button :submit, wrapper_html: { class: 'm6 s12' } %>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render 'form' %>

<%= link_to "Back", root_path %>

app/views/books/index.html.erb
<% @books.each do |book| %>
  <h2><%= link_to book.title, book_path(book) %></h2>
<% end %>

<%= link_to "Add Book", new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<h2><%= @book.title %></h2>
<h3><%= @book.author %></h3>
<p><%= @book.description %></p>

<%= link_to "Back", root_path %>
<%= link_to "Edit", edit_book_path(@book) %>
<%= link_to "Delete", book_path(@book), method: :delete, data: { confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookReview</title>
    <%= csrf_meta_tags %>
    <!-- Application.scss -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- Material Design Fonts -->
    <%= stylesheet_link_tag '//fonts.googleapis.com/css?family=Roboto:300,400,500,700', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '//fonts.googleapis.com/icon?family=Material+Icons', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap Material Design -->
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/4.0.2/bootstrap-material-design.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>